name: kaggle
channels: !!python/tuple
- menpo
- defaults
dependencies:
- appnope=0.1.0=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_1
- entrypoints=0.2.2=py35_0
- freetype=2.5.5=1
- h5py=2.6.0=np111py35_2
- hdf5=1.8.17=1
- icu=54.1=0
- ipykernel=4.5.2=py35_0
- ipython=5.1.0=py35_1
- ipython_genutils=0.1.0=py35_0
- jbig=2.1=0
- jinja2=2.8=py35_1
- jpeg=8d=2
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.1=py35_0
- libpng=1.6.22=0
- libtiff=4.0.6=2
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_1
- menpo::ipywidgets=5.1.5=py35_0
- menpo::widgetsnbextension=1.2.3=py35_1
- mistune=0.7.3=py35_1
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.2.0=py35_0
- nltk=3.2.2=py35_0
- notebook=4.2.3=py35_0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pandas=0.19.1=np111py35_0
- path.py=8.2.1=py35_0
- patsy=0.4.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=3.4.2=py35_0
- pip=9.0.1=py35_1
- prompt_toolkit=1.0.9=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_0
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- pyzmq=16.0.2=py35_0
- qt=5.6.0=0
- qtconsole=4.2.1=py35_1
- readline=6.2=2
- scikit-learn=0.18.1=np111py35_0
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- statsmodels=0.6.1=np111py35_1
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.4.2=py35_0
- traitlets=4.3.1=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - cloudpickle==0.2.2
  - cymem==1.31.2
  - ipython-genutils==0.1.0
  - javaobj-py3==0.2.3
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - keras==1.1.2
  - murmurhash==0.26.4
  - pathlib==1.0.1
  - plac==0.9.6
  - preshed==0.46.4
  - prompt-toolkit==1.0.9
  - protobuf==3.1.0.post1
  - py4j==0.10.4
  - pyyaml==3.12
  - semver==2.7.3
  - spacy==1.5.1
  - sputnik==0.9.3
  - tensorflow==0.12.1
  - theano==0.8.2
  - thinc==5.0.8
  - ujson==1.35
prefix: /Users/datitran/anaconda/envs/kaggle

